package binaryclock;

import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.awt.Rectangle;

/**
 *
 * @author Vatsal
 */
public class BinaryClockFrame extends javax.swing.JFrame {

    /**
     * Creates new form BinaryClockFrame
     */
    public BinaryClockFrame() {
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        GraphicsDevice defaultScreen = ge.getDefaultScreenDevice();
        Rectangle rect = defaultScreen.getDefaultConfiguration().getBounds();
        int x = (int) rect.getMaxX() - 450;
        int y = 0;
        this.setLocation(x, y);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        hours8 = new javax.swing.JPanel();
        hours4 = new javax.swing.JPanel();
        hours2 = new javax.swing.JPanel();
        hours1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        mins32 = new javax.swing.JPanel();
        mins16 = new javax.swing.JPanel();
        mins8 = new javax.swing.JPanel();
        mins4 = new javax.swing.JPanel();
        mins2 = new javax.swing.JPanel();
        mins1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        secs1 = new javax.swing.JPanel();
        secs8 = new javax.swing.JPanel();
        secs4 = new javax.swing.JPanel();
        secs32 = new javax.swing.JPanel();
        secs16 = new javax.swing.JPanel();
        secs2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        ampm = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 200));
        setMinimumSize(new java.awt.Dimension(400, 200));
        setUndecorated(true);

        main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(67, 146, 241));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Miriam Fixed", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Binary Clock");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 260, 40));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("X");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 40, 40));

        main.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 40));

        jPanel2.setBackground(new java.awt.Color(0, 100, 148));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Miriam Fixed", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("AM(0)/PM(1)");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 120, 30));

        hours8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        hours8.setMaximumSize(new java.awt.Dimension(25, 25));
        hours8.setMinimumSize(new java.awt.Dimension(25, 25));
        hours8.setPreferredSize(new java.awt.Dimension(25, 25));

        javax.swing.GroupLayout hours8Layout = new javax.swing.GroupLayout(hours8);
        hours8.setLayout(hours8Layout);
        hours8Layout.setHorizontalGroup(
            hours8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );
        hours8Layout.setVerticalGroup(
            hours8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        jPanel2.add(hours8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        hours4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        hours4.setMaximumSize(new java.awt.Dimension(25, 25));
        hours4.setMinimumSize(new java.awt.Dimension(25, 25));
        hours4.setPreferredSize(new java.awt.Dimension(25, 25));

        javax.swing.GroupLayout hours4Layout = new javax.swing.GroupLayout(hours4);
        hours4.setLayout(hours4Layout);
        hours4Layout.setHorizontalGroup(
            hours4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );
        hours4Layout.setVerticalGroup(
            hours4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        jPanel2.add(hours4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        hours2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        hours2.setMaximumSize(new java.awt.Dimension(25, 25));
        hours2.setMinimumSize(new java.awt.Dimension(25, 25));

        javax.swing.GroupLayout hours2Layout = new javax.swing.GroupLayout(hours2);
        hours2.setLayout(hours2Layout);
        hours2Layout.setHorizontalGroup(
            hours2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );
        hours2Layout.setVerticalGroup(
            hours2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        jPanel2.add(hours2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 25, 25));

        hours1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        hours1.setMaximumSize(new java.awt.Dimension(25, 25));
        hours1.setMinimumSize(new java.awt.Dimension(25, 25));

        javax.swing.GroupLayout hours1Layout = new javax.swing.GroupLayout(hours1);
        hours1.setLayout(hours1Layout);
        hours1Layout.setHorizontalGroup(
            hours1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );
        hours1Layout.setVerticalGroup(
            hours1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        jPanel2.add(hours1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 25, 25));

        jLabel3.setFont(new java.awt.Font("Miriam Fixed", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Hours");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 60, 30));

        mins32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        mins32.setMaximumSize(new java.awt.Dimension(25, 25));
        mins32.setMinimumSize(new java.awt.Dimension(25, 25));

        javax.swing.GroupLayout mins32Layout = new javax.swing.GroupLayout(mins32);
        mins32.setLayout(mins32Layout);
        mins32Layout.setHorizontalGroup(
            mins32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );
        mins32Layout.setVerticalGroup(
            mins32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        jPanel2.add(mins32, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 25, 25));

        mins16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        mins16.setMaximumSize(new java.awt.Dimension(25, 25));
        mins16.setMinimumSize(new java.awt.Dimension(25, 25));

        javax.swing.GroupLayout mins16Layout = new javax.swing.GroupLayout(mins16);
        mins16.setLayout(mins16Layout);
        mins16Layout.setHorizontalGroup(
            mins16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );
        mins16Layout.setVerticalGroup(
            mins16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        jPanel2.add(mins16, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 25, 25));

        mins8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        mins8.setMaximumSize(new java.awt.Dimension(25, 25));
        mins8.setMinimumSize(new java.awt.Dimension(25, 25));

        javax.swing.GroupLayout mins8Layout = new javax.swing.GroupLayout(mins8);
        mins8.setLayout(mins8Layout);
        mins8Layout.setHorizontalGroup(
            mins8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );
        mins8Layout.setVerticalGroup(
            mins8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        jPanel2.add(mins8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 25, 25));

        mins4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        mins4.setMaximumSize(new java.awt.Dimension(25, 25));
        mins4.setMinimumSize(new java.awt.Dimension(25, 25));

        javax.swing.GroupLayout mins4Layout = new javax.swing.GroupLayout(mins4);
        mins4.setLayout(mins4Layout);
        mins4Layout.setHorizontalGroup(
            mins4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );
        mins4Layout.setVerticalGroup(
            mins4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        jPanel2.add(mins4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 25, 25));

        mins2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        mins2.setMaximumSize(new java.awt.Dimension(25, 25));
        mins2.setMinimumSize(new java.awt.Dimension(25, 25));

        javax.swing.GroupLayout mins2Layout = new javax.swing.GroupLayout(mins2);
        mins2.setLayout(mins2Layout);
        mins2Layout.setHorizontalGroup(
            mins2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );
        mins2Layout.setVerticalGroup(
            mins2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        jPanel2.add(mins2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 25, 25));

        mins1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        mins1.setMaximumSize(new java.awt.Dimension(25, 25));
        mins1.setMinimumSize(new java.awt.Dimension(25, 25));

        javax.swing.GroupLayout mins1Layout = new javax.swing.GroupLayout(mins1);
        mins1.setLayout(mins1Layout);
        mins1Layout.setHorizontalGroup(
            mins1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );
        mins1Layout.setVerticalGroup(
            mins1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        jPanel2.add(mins1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 25, 25));

        jLabel4.setFont(new java.awt.Font("Miriam Fixed", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Mins");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 60, 30));

        secs1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        secs1.setMaximumSize(new java.awt.Dimension(25, 25));
        secs1.setMinimumSize(new java.awt.Dimension(25, 25));

        javax.swing.GroupLayout secs1Layout = new javax.swing.GroupLayout(secs1);
        secs1.setLayout(secs1Layout);
        secs1Layout.setHorizontalGroup(
            secs1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );
        secs1Layout.setVerticalGroup(
            secs1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        jPanel2.add(secs1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 25, 25));

        secs8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        secs8.setMaximumSize(new java.awt.Dimension(25, 25));
        secs8.setMinimumSize(new java.awt.Dimension(25, 25));

        javax.swing.GroupLayout secs8Layout = new javax.swing.GroupLayout(secs8);
        secs8.setLayout(secs8Layout);
        secs8Layout.setHorizontalGroup(
            secs8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );
        secs8Layout.setVerticalGroup(
            secs8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        jPanel2.add(secs8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 25, 25));

        secs4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        secs4.setMaximumSize(new java.awt.Dimension(25, 25));
        secs4.setMinimumSize(new java.awt.Dimension(25, 25));

        javax.swing.GroupLayout secs4Layout = new javax.swing.GroupLayout(secs4);
        secs4.setLayout(secs4Layout);
        secs4Layout.setHorizontalGroup(
            secs4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );
        secs4Layout.setVerticalGroup(
            secs4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        jPanel2.add(secs4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 25, 25));

        secs32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        secs32.setMaximumSize(new java.awt.Dimension(25, 25));
        secs32.setMinimumSize(new java.awt.Dimension(25, 25));

        javax.swing.GroupLayout secs32Layout = new javax.swing.GroupLayout(secs32);
        secs32.setLayout(secs32Layout);
        secs32Layout.setHorizontalGroup(
            secs32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );
        secs32Layout.setVerticalGroup(
            secs32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        jPanel2.add(secs32, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 25, 25));

        secs16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        secs16.setMaximumSize(new java.awt.Dimension(25, 25));
        secs16.setMinimumSize(new java.awt.Dimension(25, 25));

        javax.swing.GroupLayout secs16Layout = new javax.swing.GroupLayout(secs16);
        secs16.setLayout(secs16Layout);
        secs16Layout.setHorizontalGroup(
            secs16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );
        secs16Layout.setVerticalGroup(
            secs16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        jPanel2.add(secs16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 25, 25));

        secs2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        secs2.setMaximumSize(new java.awt.Dimension(25, 25));
        secs2.setMinimumSize(new java.awt.Dimension(25, 25));

        javax.swing.GroupLayout secs2Layout = new javax.swing.GroupLayout(secs2);
        secs2.setLayout(secs2Layout);
        secs2Layout.setHorizontalGroup(
            secs2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );
        secs2Layout.setVerticalGroup(
            secs2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        jPanel2.add(secs2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 25, 25));

        jLabel5.setFont(new java.awt.Font("Miriam Fixed", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Secs");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 60, 30));

        ampm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        ampm.setMaximumSize(new java.awt.Dimension(25, 25));
        ampm.setMinimumSize(new java.awt.Dimension(25, 25));

        javax.swing.GroupLayout ampmLayout = new javax.swing.GroupLayout(ampm);
        ampm.setLayout(ampmLayout);
        ampmLayout.setHorizontalGroup(
            ampmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );
        ampmLayout.setVerticalGroup(
            ampmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        jPanel2.add(ampm, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 25, 25));

        main.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 400, 160));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel ampm;
    public javax.swing.JPanel hours1;
    public javax.swing.JPanel hours2;
    public javax.swing.JPanel hours4;
    public javax.swing.JPanel hours8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel main;
    public javax.swing.JPanel mins1;
    public javax.swing.JPanel mins16;
    public javax.swing.JPanel mins2;
    public javax.swing.JPanel mins32;
    public javax.swing.JPanel mins4;
    public javax.swing.JPanel mins8;
    public javax.swing.JPanel secs1;
    public javax.swing.JPanel secs16;
    public javax.swing.JPanel secs2;
    public javax.swing.JPanel secs32;
    public javax.swing.JPanel secs4;
    public javax.swing.JPanel secs8;
    // End of variables declaration//GEN-END:variables
}